version: 2
updates:
  - package-ecosystem: docker
    directories:
      - "prometheus
      - "radarr"
      - "sabnzbd"
      - "sonarr"
    schedule:
      interval: "daily"
    groups:
      docker:
        patterns:
          - "*"
