version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: docker
    directories:
      - "certbot"
      - "radarr"
      - "sabnzbd"
      - "soju"
      - "sonarr"
    schedule:
      interval: "daily"
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: "daily"
