version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      github-actions:
        patterns:
          - "*"
  - package-ecosystem: docker
    directories:
      - "certbot"
      - "radarr"
      - "sabnzbd"
      - "sonarr"
    schedule:
      interval: "daily"
    groups:
      docker:
        patterns:
          - "*"
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      python:
        patterns:
          - "*"
