version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: ".github/workflows"
    schedule:
      interval: "weekly"
    groups:
      github-actions:
        patterns:
          - "*"
  - package-ecosystem: docker
    directories:
      - "*"
    schedule:
      interval: "daily"
    groups:
      docker:
        patterns:
          - "*"
