name: alpine
on:
  push:
    branches: [main]
    paths:
      - 'alpine/Dockerfile'
  workflow_dispatch:
jobs:
  build:
    runs-on: [ubuntu-latest]
    permissions:
      packages: write
    steps:
      - name: uses actions/checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2
      - name: docker login
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: docker build
        run: docker build -t ghcr.io/khorwood/${{ github.workflow }} .
        working-directory: ${{ github.workflow }}
      - name: docker push
        run: docker push ghcr.io/khorwood/${{ github.workflow }}:latest
        working-directory: ${{ github.workflow }}
