name: force-release
on:
  workflow_dispatch:
    inputs:
      container:
        type: choice
        options:
          - alpine
          - certbot
          - radarr
          - sabnzbd
          - soju
          - sonarr
jobs:
  build:
    runs-on: [ubuntu-latest]
    permissions:
      packages: write
      security-events: write
    steps:
      - name: uses actions/checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2
      - name: download alpine minirootfs
        if: ${{ github.event.inputs.container == 'alpine' }}
        run: ./fetch-minirootfs.sh
        working-directory: ${{ github.event.inputs.container }}
      - name: docker login
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: docker build
        run: docker build -t ghcr.io/khorwood/${{ github.event.inputs.container }} .
        working-directory: ${{ github.event.inputs.container }}
      - name: docker push
        run: docker push ghcr.io/khorwood/${{ github.event.inputs.container }}:latest
        working-directory: ${{ github.event.inputs.container }}
      - name: uses aquasecurity/trivy-action
        uses: aquasecurity/trivy-action@18f2510ee396bbf400402947b394f2dd8c87dbb0 #0.29.0
        env:
          TRIVY_DB_REPOSITORY: "public.ecr.aws/aquasecurity/trivy-db:2"
          TRIVY_JAVA_DB_REPOSITORY: "public.ecr.aws/aquasecurity/trivy-java-db:1"
        with:
          image-ref: 'ghcr.io/khorwood/${{ github.event.inputs.container }}:latest'
          format: 'sarif'
          output: 'trivy-results.sarif'
      - name: uses github/codeql-action/upload-sarif
        uses: github/codeql-action/upload-sarif@b56ba49b26e50535fa1e7f7db0f4f7b4bf65d80d #v3.28.10
        with:
          sarif_file: 'trivy-results.sarif'
