name: force-release
on:
  workflow_dispatch:
    inputs:
      container:
        type: choice
        options:
          - alpine
          - radarr
          - sabnzbd
          - sonarr
jobs:
  build:
    runs-on: [ubuntu-latest]
    permissions:
      packages: write
      security-events: write
    steps:
      - uses: khorwood/third-party-actions@actions/checkout/v4
      - name: download alpine minirootfs
        if: ${{ github.event.inputs.container == 'alpine' }}
        run: ./fetch-minirootfs.sh
        working-directory: ${{ github.event.inputs.container }}
      - name: docker login
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: docker build
        run: docker build -t ghcr.io/khorwood/${{ github.event.inputs.container }} .
        working-directory: ${{ github.event.inputs.container }}
      - name: docker push
        run: docker push ghcr.io/khorwood/${{ github.event.inputs.container }}:latest
        working-directory: ${{ github.event.inputs.container }}
      - uses: khorwood/third-party-actions@aquasecurity/trivy-action/v0
        env:
          TRIVY_DB_REPOSITORY: "public.ecr.aws/aquasecurity/trivy-db:2"
          TRIVY_JAVA_DB_REPOSITORY: "public.ecr.aws/aquasecurity/trivy-java-db:1"
        with:
          image-ref: 'ghcr.io/khorwood/${{ github.event.inputs.container }}:latest'
          format: 'sarif'
          output: 'trivy-results.sarif'
      - uses: khorwood/third-party-actions/upload-sarif@github/codeql-action/v3
        with:
          sarif_file: 'trivy-results.sarif'
