name: pull-request
on:
  pull_request:
    branches: [main]
jobs:
  test:
    runs-on: [ubuntu-latest]
    strategy:
      matrix:
        container: [certbot, radarr, sabnzbd, soju, sonarr]
    steps:
      - name: uses actions/checkout
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 #v4.2.1
      - name: uses hadolint/hadolint-action
        uses: hadolint/hadolint-action@54c9adbab1582c2ef04b2016b760714a4bfde3cf #v3.1.0
        with:
          dockerfile: ${{ matrix.container }}/Dockerfile
