name: pull-request
on:
  pull_request:
    branches: [main]
jobs:
  test:
    runs-on: [ubuntu-latest]
    strategy:
      matrix:
        container: [certbot, radarr, sabnzbd, soju, sonarr, yarr]
    steps:
      - name: uses actions/checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2
      - name: uses hadolint/hadolint-action
        uses: hadolint/hadolint-action@54c9adbab1582c2ef04b2016b760714a4bfde3cf #v3.1.0
        with:
          dockerfile: ${{ matrix.container }}/Dockerfile
      - name: docker build
        run: docker build .
        working-directory: ${{ matrix.container }}
