name: pull-request
on:
  pull_request:
    branches: [main]
jobs:
  changed:
    runs-on: [ubuntu-latest]
    outputs:
      matrix: ${{ steps.changes.outputs.matrix }}
    steps:
      - name: uses hellofresh/action-changed-files
        uses: hellofresh/action-changed-files@f6db62a551af02bb4bbc88ce6536bf40aa537e8f #v3.0.1
        id: changes
        with:
          pattern: (?P<container>(?!\.github)[^/]+)
  test:
    runs-on: [ubuntu-latest]
    needs: changed
    strategy:
      matrix: ${{ fromJson(needs.changed.outputs.matrix) }}
    if: ${{ fromJson(needs.changed.outputs.matrix).include[0] }}
    steps:
      - name: uses actions/checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2
      - name: download alpine minirootfs
        if: ${{ matrix.container == 'alpine' }}
        run: ./fetch-minirootfs.sh
        working-directory: ${{ matrix.container }}
      - name: uses hadolint/hadolint-action
        uses: hadolint/hadolint-action@54c9adbab1582c2ef04b2016b760714a4bfde3cf #v3.1.0
        with:
          dockerfile: ${{ matrix.container }}/Dockerfile
      - name: docker build
        run: docker build -t ghcr.io/khorwood/${{ matrix.container }}:${{ github.sha }} .
        working-directory: ${{ matrix.container }}
      - name: uses aquasecurity/trivy-action
        uses: aquasecurity/trivy-action@18f2510ee396bbf400402947b394f2dd8c87dbb0 #0.29.0
        env:
          TRIVY_DB_REPOSITORY: "public.ecr.aws/aquasecurity/trivy-db:2"
          TRIVY_JAVA_DB_REPOSITORY: "public.ecr.aws/aquasecurity/trivy-java-db:1"
        with:
          image-ref: 'ghcr.io/khorwood/${{ matrix.container }}:${{ github.sha }}'
          format: 'sarif'
          output: 'trivy-results.sarif'
      - name: uses github/codeql-action/upload-sarif
        uses: github/codeql-action/upload-sarif@17a820bf2e43b47be2c72b39cc905417bc1ab6d0 #v3.28.6
        with:
          sarif_file: 'trivy-results.sarif'
