name: pull-request
on:
  pull_request:
    branches: [main]
    paths:
      - "**/Dockerfile"
      - "**/requirements.txt"
      - "**/*.sh"
jobs:
  changes:
    runs-on: [ubuntu-latest]
    steps:
      - name: uses actions/checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2
      - name: uses tj-actions/changed-files
        id: changed
        uses: tj-actions/changed-files@4edd678ac3f81e2dc578756871e4d00c19191daf #v45.0.4
        with:
          dir_names: "true"
    outputs:
      matrix: ${{ steps.changed.outputs.all_changed_files }}
  test:
    runs-on: [ubuntu-latest]
    needs: changes
    strategy:
      matrix:
        container: ${{ needs.changes.outputs.matrix }}
    steps:
      - name: uses actions/checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2
      - name: uses hadolint/hadolint-action
        uses: hadolint/hadolint-action@54c9adbab1582c2ef04b2016b760714a4bfde3cf #v3.1.0
        with:
          dockerfile: ${{ matrix.container }}/Dockerfile
      - name: docker build
        if: ${{ steps.changes.outputs.stdout != '' }}
        run: docker build .
        working-directory: ${{ matrix.container }}
