name: release
on:
  push:
    branches: [main]
  workflow_dispatch:
permissions:
  contents: read
jobs:
  changed:
    runs-on: [ubuntu-latest]
    outputs:
      matrix: ${{ steps.changes.outputs.matrix }}
    steps:
      - uses: khorwood/third-party-actions@hellofresh/action-changed-files/v3
        id: changes
        with:
          pattern: (?P<container>(?!\.github)[^/]+)
  build:
    runs-on: [ubuntu-latest]
    needs: changed
    permissions:
      actions: read
      packages: write
      security-events: write
    strategy:
      matrix: ${{ fromJson(needs.changed.outputs.matrix) }}
    if: ${{ fromJson(needs.changed.outputs.matrix).include[0] }}
    steps:
      - uses: khorwood/third-party-actions@actions/checkout/v4
      - name: download alpine minirootfs
        if: ${{ matrix.container == 'alpine' }}
        run: ./fetch-minirootfs.sh
        working-directory: ${{ matrix.container }}
      - name: docker login
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: docker build
        run: docker build -t ghcr.io/khorwood/${{ matrix.container }} .
        working-directory: ${{ matrix.container }}
      - name: docker push
        run: docker push ghcr.io/khorwood/${{ matrix.container }}:latest
        working-directory: ${{ matrix.container }}
      - uses: khorwood/third-party-actions@aquasecurity/trivy-action/v0
        env:
          TRIVY_DB_REPOSITORY: "public.ecr.aws/aquasecurity/trivy-db:2"
          TRIVY_JAVA_DB_REPOSITORY: "public.ecr.aws/aquasecurity/trivy-java-db:1"
        with:
          image-ref: 'ghcr.io/khorwood/${{ matrix.container }}:latest'
          format: 'sarif'
          output: 'trivy-results.sarif'
      - uses: khorwood/third-party-actions/upload-sarif@github/codeql-action/v3
        with:
          sarif_file: 'trivy-results.sarif'
