name: sonarr
on:
  pull_request:
    branches: [main]
    paths:
      - ".github/workflows/sonarr.yml"
      - "sonarr/**"
  push:
    branches: [main]
    paths:
      - ".github/workflows/sonarr.yml"
      - "sonarr/**"
  workflow_dispatch:
env:
  RELEASE: "4.0.15.2941"
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      security-events: write
    steps:
      - uses: actions/checkout@v4
      - run: |
            docker buildx build \
                --build-arg RELEASE=${{ env.RELEASE }} \
                -t ghcr.io/khorwood/sonarr:${{ env.RELEASE }}-${{ github.run_number }} .
        working-directory: sonarr
      - uses: aquasecurity/trivy-action@0.32.0
        env:
          TRIVY_DB_REPOSITORY: "public.ecr.aws/aquasecurity/trivy-db:2"
          TRIVY_JAVA_DB_REPOSITORY: "public.ecr.aws/aquasecurity/trivy-java-db:1"
        with:
          image-ref: 'ghcr.io/khorwood/sonarr:${{ env.RELEASE }}-${{ github.run_number }}'
          format: 'sarif'
          output: 'trivy-results.sarif'
      - name: docker login
        if: github.ref == 'refs/heads/main'
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: docker push
        if: github.ref == 'refs/heads/main'
        run: docker push ghcr.io/khorwood/sonarr:${{ env.RELEASE }}-${{ github.run_number }}
        working-directory: sonarr
